name: Build Electron App

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows Portable
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with webpack
        run: npm run webpack

      - name: Build Electron portable
        run: npx electron-builder --win portable

      - name: Upload portable executable
        uses: actions/upload-artifact@v4
        with:
          name: task-manager-windows-portable
          path: |
            dist/*.exe
          retention-days: 30

  create-release:
    name: Create GitHub Release
    needs: build-windows
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download portable executable
        uses: actions/download-artifact@v4
        with:
          name: task-manager-windows-portable
          path: ./release-files

      - name: Display downloaded files
        run: ls -la release-files/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-files/*.exe
          body: |
            Windows Portable Edition

            **Task Manager** - Modern task manager with hierarchical graph visualization

            Changes in ${{ github.ref_name }}:
            - See commit history for details
          draft: false
          prerelease: false
